"""users-2

Revision ID: 362d1e6e8e3d
Revises: e06c3d4793e2
Create Date: 2026-03-07 03:29:26.134802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '362d1e6e8e3d'
down_revision: Union[str, None] = 'e06c3d4793e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('usuarios', sa.Column('magic_token', sa.String(length=64), nullable=True))
    op.add_column('usuarios', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_usuarios_magic_token'), 'usuarios', ['magic_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_magic_token'), table_name='usuarios')
    op.drop_column('usuarios', 'token_expires_at')
    op.drop_column('usuarios', 'magic_token')
    
    # ### end Alembic commands ###