"""users

Revision ID: e06c3d4793e2
Revises: ffc88bb9a462
Create Date: 2026-03-06 05:26:27.732127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e06c3d4793e2'
down_revision: Union[str, None] = 'ffc88bb9a462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tiendanube_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('tarjetas_qr',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('puntos_asignados', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarjetas_qr_codigo'), 'tarjetas_qr', ['codigo'], unique=True)
    op.create_index(op.f('ix_tarjetas_qr_estado'), 'tarjetas_qr', ['estado'], unique=False)
    op.create_index(op.f('ix_tarjetas_qr_usuario_id'), 'tarjetas_qr', ['usuario_id'], unique=False)
    
    op.add_column('puntos_ledger', sa.Column('tarjeta_origen_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'puntos_ledger', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'puntos_ledger', 'tarjetas_qr', ['tarjeta_origen_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'puntos_ledger', type_='foreignkey')
    op.drop_constraint(None, 'puntos_ledger', type_='foreignkey')
    op.drop_column('puntos_ledger', 'tarjeta_origen_id')
    
    op.drop_index(op.f('ix_tarjetas_qr_usuario_id'), table_name='tarjetas_qr')
    op.drop_index(op.f('ix_tarjetas_qr_estado'), table_name='tarjetas_qr')
    op.drop_index(op.f('ix_tarjetas_qr_codigo'), table_name='tarjetas_qr')
    op.drop_table('tarjetas_qr')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###