"""ledger

Revision ID: ffc88bb9a462
Revises: 
Create Date: 2026-03-03 15:43:02.190665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffc88bb9a462'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puntos_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puntos_ledger_usuario_id'), 'puntos_ledger', ['usuario_id'], unique=False)
    op.add_column('products', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('products', sa.Column('tiendanube_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('tiendanube_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('ai_description_proposal', sa.Text(), nullable=True))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_column('products', 'ai_description_proposal')
    op.drop_column('products', 'tiendanube_url')
    op.drop_column('products', 'tiendanube_id')
    op.drop_column('products', 'sku')
    
    op.drop_index(op.f('ix_puntos_ledger_usuario_id'), table_name='puntos_ledger')
    op.drop_table('puntos_ledger')
    # ### end Alembic commands ###